# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4630df286528de67e0c06dc4d7d6ca7a3654a57e20aaf1fcc1b6fda00427bc2cb59ce87a0b428953af02da391c2bcfdf7087ff8e15d81949323bf81a681c52

test:
  secret_key_base: 377bd7329afbd19b48972abf725b20e09efa79a1d3aeb8e9ba1c71d5de1a17ad89755ecda8510fc1360696d587933de5f5f67395e88ff0fa8a9a3c940424cafa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
